# Generated by Django 2.0.3 on 2019-06-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190525_0733'),
        ('carts', '0003_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('variations', models.TextField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Product')),
            ],
        ),
    ]
