# Generated by Django 2.0.3 on 2019-06-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cartitem_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
