# Generated by Django 2.0.3 on 2019-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_variation'),
        ('carts', '0008_auto_20190605_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='order.Variation'),
        ),
    ]
