# Generated by Django 2.0.3 on 2019-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('regular-pizza', 'regular-pizza'), ('sicilian-pizza', 'sicilian-pizza'), ('subs', 'subs'), ('pasta', 'pasta'), ('salads', 'salads'), ('dinner-platters', 'dinner-platters')], default='regular-pizza', max_length=64),
        ),
    ]
