# Generated by Django 2.0.3 on 2019-06-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.AddField(
            model_name='product',
            name='topping_qty',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
