# Generated by Django 2.0.3 on 2019-06-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20190609_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='topping_qty',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='variation',
            name='products',
        ),
        migrations.AddField(
            model_name='variation',
            name='products',
            field=models.ManyToManyField(to='order.Product'),
        ),
    ]
